var btnTranslate = document.querySelector("#btn-translate");
var inputText = document.querySelector('#input-text');
var outputText = document.querySelector("#output-text");

function getTranslationText(text){
  var texte = text.toLowerCase();
  outputText.innerTex ="";
  for(var i = 0; i < words.length; i++)
  {
    if(words[i].word.fr == texte)
    {
      outputText.innerText = words[i].word.wo;
      return;
    }
  }
  outputText.innerText ="We try. on essaye . danniy essayer . 試しに";
  return;
}

function errorHandler(error){
    console.log("error occured",error)
}
function clickEventHandler(){
    // outputText.innerText=inputText.value;

    var inputTxt = inputText.value;
    getTranslationText(inputTxt);

}
btnTranslate.addEventListener("click",clickEventHandler)

words =
  [
    {"word" : { "fr" : "bonjour", "wo" : "naga def" }},
    {"word" : { "fr" : "hello", "wo" : "naga def" }},
    {"word" : { "fr" : "こんにちは", "wo" : "naga def" }},
    {"word" : { "fr" : "un", "wo" : "benn" }},
    {"word" : { "fr" : "deux", "wo" : "ñaar" }},
    {"word" : { "fr" : "trois", "wo" : "ñett" }},
    {"word" : { "fr" : "quatre", "wo" : "ñeent" }},
    {"word" : { "fr" : "cinq", "wo" : "juróom" }},
    {"word" : { "fr" : "six", "wo" : "juróom-benn" }},
    {"word" : { "fr" : "sept", "wo" : "juróom-ñaar" }},
    {"word" : { "fr" : "huit", "wo" : "juróom-ñett" }},
    {"word" : { "fr" : "neuf", "wo" : "juróom-ñeent" }},
    {"word" : { "fr" : "dix", "wo" : "fukk" }},
    {"word" : { "fr" : "onze", "wo" : "fukk ak benn"}},
    {"word" : { "fr" : "douze", "wo" : "fukk ak ñaar"}},
    {"word" : { "fr" : "treize", "wo" : "fukk ak ñett"}},
    {"word" : { "fr" : "quatorze", "wo" : "fukk ak ñeent"}},
    {"word" : { "fr" : "quinze", "wo" : "fukk ak juróom"}},
    {"word" : { "fr" : "seize", "wo" : "fukk ak juróom-benn"}},
    {"word" : { "fr" : "dix-sept", "wo" : "fukk ak juróom-ñaar"}},
    {"word" : { "fr" : "dix-huit", "wo" : "fukk ak juróom-ñett"}},
    {"word" : { "fr" : "dix-neuf", "wo" : "fukk ak juróom-ñeent"}},
    {"word" : { "fr" : "vingt", "wo" : "ñaar-fukk"}},
    {"word" : { "fr" : "vingt-six", "wo" : "ñaar-fukk ak juróom-benn"}},
    {"word" : { "fr" : "trente", "wo" : "ñett-fukk", "fanweer"}},
    {"word" : { "fr" : "quarante", "wo" : "ñeent-fukk"}},
    {"word" : { "fr" : "cinquante", "wo" : "juróom-fukk"}},
    {"word" : { "fr" : "soixante", "wo" : "juróom-benn-fukk"}},
    {"word" : { "fr" : "soixante-six", "wo" : "juróom-benn-fukk ak juróom-benn"}},
    {"word" : { "fr" : "soixante-dix", "wo" : "juróom-ñaar-fukk"}},
    {"word" : { "fr" : "quatre vingt", "wo" : "juróom-ñett-fukk"}},
    {"word" : { "fr" : "quatre vingt dix", "wo" : "juróom-ñeent-fukk"}},
    {"word" : { "fr" : "cent", "wo" : "téeméer"}},
    {"word" : { "fr" : "cent un", "wo" : "téeméer ak benn"}},
    {"word" : { "fr" : "cent six", "wo" : "téeméer ak juróom-benn"}},
    {"word" : { "fr" : "cent dix", "wo" : "téeméer ak fukk"}},
    {"word" : { "fr" : "deux cent", "wo" : "ñaari téeméer"}},
    {"word" : { "fr" : "trois cent", "wo" : "ñetti téeméer"}},
    {"word" : { "fr" : "quatre cent", "wo" : "ñeenti téeméer"}},
    {"word" : { "fr" : "cinq cent", "wo" : "juróomi téeméer"}},
    {"word" : { "fr" : "six cent", "wo" : "juróom-benni téeméer"}},
    {"word" : { "fr" : "sept cent", "wo" : "juróom-ñaari téeméer"}},
    {"word" : { "fr" : "huit cent", "wo" : "juróom-ñetti téeméer"}},
    {"word" : { "fr" : "neuf cent", "wo" : "juróom-ñeenti téeméer"}},
    {"word" : { "fr" : "mille", "wo" : "junni", "junne"}},
    {"word" : { "fr" : "mille cent", "wo" : "junni ak téeméer"}},
    {"word" : { "fr" : "mille six cent", "wo" : "junni ak juróom-benni téeméer"}},
    {"word" : { "fr" : "mille neuf cent quarante cinq", "wo" : "junni ak juróom-ñeenti téeméer ak ñeent-fukk ak juróom"}},
    {"word" : { "fr" : "mille neuf cent soixante neuf", "wo" : "junni ak juróom-ñeenti téeméer ak juróom-benn-fukk ak juróom-ñeent"}},
    {"word" : { "fr" : "deux mille", "wo" : "ñaari junni"}},
    {"word" : { "fr" : "trois mille", "wo" : "ñetti junni"}},
    {"word" : { "fr" : "quatre mille", "wo" : "ñeenti junni"}},
    {"word" : { "fr" : "cinq mille", "wo" : "juróomi junni"}},
    {"word" : { "fr" : "six mille", "wo" : "juróom-benni junni"}},
    {"word" : { "fr" : "sept mille", "wo" : "juróom-ñaari junni"}},
    {"word" : { "fr" : "huit mille", "wo" : "juróom-ñetti junni"}},
    {"word" : { "fr" : "neuf mille", "wo" : "juróom-ñeenti junni"}},
    {"word" : { "fr" : "dix mille", "wo" : "fukki junni"}},
    {"word" : { "fr" : "cent mille", "wo" : "téeméeri junni"}},
    {"word" : { "fr" : "million", "wo" : "tamndareet", "million"}},
    {"word" : { "fr" : "onze", "wo" : "fukk ak benn"}},
    {"word" : { "fr" : "douze", "wo" : "fukk ak ñaar"}},
    {"word" : { "fr" : "treize", "wo" : "fukk ak ñett"}},
    {"word" : { "fr" : "quatorze", "wo" : "fukk ak ñeent"}},
    {"word" : { "fr" : "1st", "wo" : "bu njëk"}},
    {"word" : { "fr" : "2nd", "wo" : "ñaaréél"}},
    {"word" : { "fr" : "3rd", "wo" : "ñettéél"}},
    {"word" : { "fr" : "4th", "wo" : "ñeentéél"}},
    {"word" : { "fr" : "5th", "wo" : "juróoméél"}},
    {"word" : { "fr" : "6th", "wo" : "juróom-bennéél"}},
    {"word" : { "fr" : "7th", "wo" : "juróom-ñaaréél"}},
    {"word" : { "fr" : "8th", "wo" : "juróom-ñettéél"}},
    {"word" : { "fr" : "9th", "wo" : "juróom-ñeentéél"}},
    {"word" : { "fr" : "10th", "wo" : "fukkéél"}},
    {"word" : { "fr" : "", "wo" : "Mangi fii (rekk)."}},
    {"word" : { "fr" : "", "wo" : "Yaangi ci jamm?"}},
    {"word" : { "fr" : "", "wo" : "jamm rekk, Alxamdulilaay"}},
    {"word" : { "fr" : "", "wo" : "Ana sa waa ker?"}},
    {"word" : { "fr" : "", "wo" : "Ñunga fa."}},
    {"word" : { "fr" : "", "wo" : "(Bi) Ñaata (la)?"}},
    {"word" : { "fr" : "", "wo" : "Dafa cher/jaffe."}},
    {"word" : { "fr" : "", "wo" : "Waññi ko."}},
    {"word" : { "fr" : "", "wo" : "jërejëf"}},
    {"word" : { "fr" : "", "wo" : "Ñoo ko bokk."}},
    {"word" : { "fr" : "", "wo" : "waaw"}},
    {"word" : { "fr" : "", "wo" : "déedéet"}},
    {"word" : { "fr" : "", "wo" : "Dama xiif."}},
    {"word" : { "fr" : "", "wo" : "Dama mar."}},
    {"word" : { "fr" : "", "wo" : "Dama sonn."}},
    {"word" : { "fr" : "", "wo" : "Jamm ngam fanaan?"}},
    {"word" : { "fr" : "", "wo" : "jamm rekk, Alxamdulilaay"}},
    {"word" : { "fr" : "", "wo" : "Naka suba si?"}},
    {"word" : { "fr" : "", "wo" : "Suba si, sangi nii (rekk)."}},
    {"word" : { "fr" : "", "wo" : "ba ci kanam"}},
    {"word" : { "fr" : "", "wo" : "ba beneen (yoon)"}},
    {"word" : { "fr" : "", "wo" : "jamm ak jamm"}},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }},
    {"word" : { "fr" : "", "wo" : "" }}
];
